[package]
name = "day10b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
event-emitter-rs = "0.1.4"
events_emitter = "0.1.3"